---
- hosts: nodes
  remote_user: root
  tasks:
    - name: write or read with couchbase cluster
      shell: >
        java -Xmx2g -cp cbbenchmark-*.jar org.cbbenchmark.Benchmark {{ hostname|quote }}
        {{ bucketName|quote }} {{ bucketPwd|quote }}
        {{ numKeys }} {{ valueSize }} {{ timeout }}
        {{ sleepTime }} {{ numThreads }}
        {{ ratio }}
        {{ prefix|quote }}
        {{ loopTimes }} > {{ hostname|quote }}_{{ bucketName|quote }}_{{ bucketPwd|quote }}_numKeys{{ numKeys }}_valueSize{{ valueSize }}_timeout{{ timeout }}_sleepTime{{ sleepTime }}_numThreads{{ numThreads }}_ratio{{ ratio }}_prefix{{ prefix|quote }}_loopTimes{{ loopTimes }}.log
      args:
        chdir: /tmp/cbbenchmark/target
