---
- hosts: nodes
  remote_user: root
  tasks:
    - name: write or read with couchbase cluster
      shell: >
        java -Xmx2g -cp cbbenchmark-*.jar org.cbbenchmark.Benchmark {{ hostname|quote }}
        {{ bucketName|quote }} {{ bucketPwd|quote }}
        {{ numKeys }} {{ valueSize }} {{ timeout }}
        {{ sleepTime }} {{ numThreads }}
        {{ ratio }}
        {{ prefix|quote }}
        {{ loopTimes }} > {{ hostname|quote }}_{{ bucketName|quote }}_{{ bucketPwd|quote }}_{{ numKeys }}_{{ valueSize }}_{{ timeout }}_{{ sleepTime }}_{{ numThreads }}_{{ ratio }}_{{ prefix|quote }}_    {{ loopTimes }}.log
      args:
        chdir: /tmp/cbbenchmark/target
